Repository nbcampMasterChapter4Team7/TeamProject, pull requests merged in 2025-04, with the labels that each got.

#2 Setting/#1
  TeamProject/TeamProject/Resource/Assets.xcassets/kickboard.imageset/Contents.json
  TeamProject/TeamProject/Resource/Assets.xcassets/kickboard.imageset/kickboard.png
  TeamProject/TeamProject/Resource/Assets.xcassets/kickboard.imageset/kickboard@2x.png
  TeamProject/TeamProject/Resource/Assets.xcassets/kickboard.imageset/kickboard@3x.png
  TeamProject/TeamProject/Resource/Assets.xcassets/location.imageset/Contents.json
  TeamProject/TeamProject/Resource/Assets.xcassets/location.imageset/location.png
  TeamProject/TeamProject/Resource/Assets.xcassets/location.imageset/location@2x.png
  TeamProject/TeamProject/Resource/Assets.xcassets/location.imageset/location@3x.png
  TeamProject/TeamProject/Resource/Assets.xcassets/ping.imageset/Contents.json
  TeamProject/TeamProject/Resource/Assets.xcassets/ping.imageset/ping.png
  TeamProject/TeamProject/Resource/Assets.xcassets/ping.imageset/ping@2x.png
  TeamProject/TeamProject/Resource/Assets.xcassets/ping.imageset/ping@3x.png
  TeamProject/TeamProject/Resource/Colors.xcassets/Contents.json
  TeamProject/TeamProject/Resource/Colors.xcassets/Gray#0.colorset/Contents.json
  TeamProject/TeamProject/Resource/Colors.xcassets/Gray#1.colorset/Contents.json
  TeamProject/TeamProject/Resource/Colors.xcassets/Gray#2.colorset/Contents.json
  TeamProject/TeamProject/Resource/Colors.xcassets/Gray#3.colorset/Contents.json
  TeamProject/TeamProject/Resource/Colors.xcassets/Main.colorset/Contents.json
  TeamProject/TeamProject/Utility/Extensions/UIColor+.swift
  TeamProject/TeamProject/Utility/Extensions/UIFont+.swift
  TeamProject/TeamProject/Utility/Extensions/UIImage+.swift
  TeamProject/TeamProject/Utility/Literals/FontLiterals.swift
  TeamProject/TeamProject/Utility/Literals/ImageLiterals.swift
Labels: 👻 세준, ⚙ Setting

#4 Setting/#3
  .gitignore
  TeamProject/TeamProject.xcodeproj/project.pbxproj
  TeamProject/TeamProject.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  TeamProject/TeamProject.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 👻 세준, 🐞 BugFix

#9 [Feat] #7 - 하단 TabBar 추가
  README.md
  TeamProject/TeamProject/App/SceneDelegate.swift
  TeamProject/TeamProject/Utility/Literals/FontLiterals.swift
  TeamProject/TeamProject/View/RentViewController.swift
  TeamProject/TeamProject/ViewController.swift
Labels: 👻 세준, ✨ Feature

#11 [Feat] #5 - 로그인 화면 구현
  TeamProject/TeamProject/App/SceneDelegate.swift
  TeamProject/TeamProject/Utility/Extensions/KeyboardObserver+.swift
  TeamProject/TeamProject/Utility/Extensions/UITextFieldDelegate+.swift
  TeamProject/TeamProject/View/LoginView.swift
  TeamProject/TeamProject/View/MembersipView.swift
  TeamProject/TeamProject/ViewController/LoginViewController.swift
  TeamProject/TeamProject/ViewController/MembershipViewController.swift
Labels: ✨ Feature, 🐸 부용

#13 [Setting] #12 - API Key 정리
  .gitignore
  TeamProject/TeamProject.xcodeproj/project.pbxproj
  TeamProject/TeamProject/Info.plist
  TeamProject/TeamProject/MainViewController.swift
  TeamProject/TeamProject/View/LoginView/LoginViewController.swift
  TeamProject/TeamProject/View/LoginView/ViewComponents/LoginView.swift
  TeamProject/TeamProject/View/MembershipView/MembershipViewController.swift
  TeamProject/TeamProject/View/MembershipView/ViewComponents/MembershipView.swift
  TeamProject/TeamProject/View/RentView/RentViewController.swift
Labels: 👻 세준, 🐞 BugFix, ⚙ Setting

#20 [Feat] #16 - 마이페이지 화면 구현
  TeamProject/TeamProject/MainViewController.swift
  TeamProject/TeamProject/Utility/Extensions/KeyboardObserver+.swift
  TeamProject/TeamProject/Utility/Extensions/UITextFieldDelegate+.swift
  TeamProject/TeamProject/Utility/Literals/FontLiterals.swift
  TeamProject/TeamProject/View/LoginView/LoginViewController.swift
  TeamProject/TeamProject/View/LoginView/ViewComponents/LoginView.swift
  TeamProject/TeamProject/View/MembershipView/ViewComponents/MembershipView.swift
  TeamProject/TeamProject/View/MyPageView/MyPageViewComponenets/MyPageTableViewCell.swift
  TeamProject/TeamProject/View/MyPageView/MyPageViewComponenets/MyPageView.swift
  TeamProject/TeamProject/View/MyPageView/MyPageViewController.swift
  TeamProject/TeamProject/protocol/DelegateProtocol.swift
Labels: ✨ Feature, 🐸 부용

#18 [Feat] #6 - 킥보드 등록 페이지 구현
  TeamProject/APIKey.xcconfig
  TeamProject/TeamProject/App/AppDelegate.swift
  TeamProject/TeamProject/App/SceneDelegate.swift
  TeamProject/TeamProject/MainViewController.swift
  TeamProject/TeamProject/View/KickBoardRegisterView/KickBoardRegisterViewController.swift
  TeamProject/TeamProject/View/KickBoardRegisterView/RegisterKickboardAlertViewController.swift
Labels: ✨ Feature, 😈 재욱

#22 [Feat] #10 - 대여 화면 현재 위치로 지도 이동 구현
  TeamProject/TeamProject/Info.plist
  TeamProject/TeamProject/Utility/Literals/SizeLiterals.swift
  TeamProject/TeamProject/View/Common/KakaoMapViewController.swift
  TeamProject/TeamProject/View/RentView/RentViewController.swift
Labels: 👻 세준, ✨ Feature

#28 [Feat] #23 - 대여 화면 - 킥보드 대여 모달 UI
  TeamProject/KakaoAPIKey.xcconfig
  TeamProject/TeamProject/View/RentView/RentModalViewController.swift
  TeamProject/TeamProject/View/RentView/RentViewController.swift
  TeamProject/TeamProject/ViewModel/RentViewModel.swift
Labels: 👻 세준, ✨ Feature

#33 [Feat] #27 - UserDefaults 사용과 로그인 검증 로직 구현
  TeamProject/Model/RegistrationHistory.swift
  TeamProject/Model/UsageHistory.swift
  TeamProject/Model/ValidationResult.swift
  TeamProject/TeamProject.xcodeproj/project.pbxproj
  TeamProject/TeamProject/App/SceneDelegate.swift
  TeamProject/TeamProject/Utility/Extensions/KeyboardObserver+.swift
  TeamProject/TeamProject/View/LoginView/LoginViewController.swift
  TeamProject/TeamProject/View/LoginView/ViewComponents/LoginView.swift
  TeamProject/TeamProject/View/MembershipView/MembershipViewController.swift
  TeamProject/TeamProject/View/MembershipView/ViewComponents/MembershipView.swift
  TeamProject/TeamProject/View/MyPageView/MyPageViewComponenets/MyPageView.swift
  TeamProject/TeamProject/View/MyPageView/MyPageViewController.swift
  TeamProject/TeamProject/ViewModel/LoginViewModel.swift
  TeamProject/TeamProject/ViewModel/SignUpViewModel.swift
  TeamProject/UserDefaults/UserDefaultsManager.swift
Labels: ✨ Feature, 🐸 부용

#43 [Feat] #32 - 대여/반납 기능 구현
  TeamProject/Model/UsageHistory.swift
  TeamProject/TeamProject/App/SceneDelegate.swift
  TeamProject/TeamProject/CoreData/CoreDataManager.swift
  TeamProject/TeamProject/CoreData/SubClass/KickBoardRecordEntity+CoreDataClass.swift
  TeamProject/TeamProject/CoreData/SubClass/KickBoardRecordEntity+CoreDataProperties.swift
  TeamProject/TeamProject/CoreData/SubClass/UsageHistoryEntity+CoreDataClass.swift
  TeamProject/TeamProject/CoreData/SubClass/UsageHistoryEntity+CoreDataProperties.swift
  TeamProject/TeamProject/Model.xcdatamodeld/Model.xcdatamodel/contents
  TeamProject/TeamProject/Resource/Assets.xcassets/scooter.imageset/Contents.json
  TeamProject/TeamProject/Resource/Assets.xcassets/scooter.imageset/scooter.png
  TeamProject/TeamProject/Resource/Assets.xcassets/scooter.imageset/scooter@2x.png
  TeamProject/TeamProject/Resource/Assets.xcassets/scooter.imageset/scooter@3x.png
  TeamProject/TeamProject/Utility/Extensions/Date+.swift
  TeamProject/TeamProject/Utility/Extensions/UIViewController+.swift
  TeamProject/TeamProject/Utility/Literals/ImageLiterals.swift
  TeamProject/TeamProject/View/Common/KakaoMapViewController.swift
  TeamProject/TeamProject/View/LoginView/LoginViewController.swift
  TeamProject/TeamProject/View/MembershipView/MembershipViewController.swift
  TeamProject/TeamProject/View/MyPageView/MyPageViewComponenets/MyPageView.swift
  TeamProject/TeamProject/View/MyPageView/MyPageViewController.swift
  TeamProject/TeamProject/View/RentView/RentModalViewController.swift
  TeamProject/TeamProject/View/RentView/RentViewController.swift
  TeamProject/TeamProject/View/UsageHistory/UsageHistoryComponents/UsageHistoryTableViewCell.swift
  TeamProject/TeamProject/View/UsageHistory/UsageHistoryViewController.swift
  TeamProject/TeamProject/ViewModel/RentModalViewModel.swift
  TeamProject/UserDefaults/UserDefaultsManager.swift
Labels: 👻 세준, ✨ Feature

#51 [Fix] - 테이블뷰, UserDefaults 오류 수정
  TeamProject/TeamProject/App/SceneDelegate.swift
  TeamProject/TeamProject/View/LoginView/LoginViewController.swift
  TeamProject/TeamProject/View/MyPageView/MyPageViewComponenets/MyPageTableViewCell.swift
  TeamProject/TeamProject/View/RegistrationHistory/RegistrationHistoryComponents/RegistrationHistoryTableViewCell.swift
  TeamProject/TeamProject/View/UsageHistory/UsageHistoryComponents/UsageHistoryTableViewCell.swift
  TeamProject/TeamProject/ViewModel/LoginViewModel.swift
  TeamProject/TeamProject/ViewModel/SignUpViewModel.swift
  TeamProject/UserDefaults/UserDefaultsManager.swift
Labels: 🐸 부용
