Repository nbcampMasterChapter4Team7/TeamProject, pull requests merged in 2025-05, with the labels that each got.

#53 [Feat] #49 - 대여화면 기능 구현
  TeamProject/KakaoAPIKey.xcconfig
  TeamProject/Model/SearchData.swift
  TeamProject/TeamProject/Info.plist
  TeamProject/TeamProject/Resource/Assets.xcassets/marker.imageset/Contents.json
  TeamProject/TeamProject/Resource/Assets.xcassets/marker.imageset/marker.png
  TeamProject/TeamProject/Resource/Assets.xcassets/marker.imageset/marker@2x.png
  TeamProject/TeamProject/Resource/Assets.xcassets/marker.imageset/marker@3x.png
  TeamProject/TeamProject/View/Common/KakaoMapViewController.swift
  TeamProject/TeamProject/View/RentView/RentModalViewController.swift
  TeamProject/TeamProject/View/RentView/RentViewController.swift
  TeamProject/TeamProject/View/UsageHistory/UsageHistoryViewController.swift
  TeamProject/TeamProject/ViewModel/RentViewModel.swift
  TeamProject/UserDefaults/UserDefaultsManager.swift
Labels: 👻 세준, ✨ Feature

#57 [Fix] #54 - 킥보드 대여/반납시 지도 action
  TeamProject/TeamProject/View/RentView/RentModalViewController.swift
  TeamProject/TeamProject/View/RentView/RentViewController.swift
Labels: 👻 세준, 🐞 BugFix

#59 [Feat] #58 - 대여시 타이머 동작, 반납시 이용시간, 사용금액 alert
  TeamProject/TeamProject/CoreData/CoreDataManager.swift
  TeamProject/TeamProject/View/RentView/RentModalViewController.swift
  TeamProject/TeamProject/ViewModel/RentModalViewModel.swift
Labels: 👻 세준, ✨ Feature

#60 [Fix] - 이용내역 데이터 연결 재작업 및 UI 수정
  TeamProject/Model/UsageHistory.swift
  TeamProject/TeamProject/CoreData/CoreDataManager.swift
  TeamProject/TeamProject/CoreData/SubClass/UsageHistoryEntity+CoreDataProperties.swift
  TeamProject/TeamProject/Model.xcdatamodeld/Model.xcdatamodel/contents
  TeamProject/TeamProject/View/RegistrationHistory/RegistrationHistoryComponents/RegistrationHistoryTableViewCell.swift
  TeamProject/TeamProject/View/UsageHistory/UsageHistoryComponents/UsageHistoryTableViewCell.swift
  TeamProject/TeamProject/View/UsageHistory/UsageHistoryViewController.swift
  TeamProject/TeamProject/ViewModel/KickBoardRecordViewModel.swift
  TeamProject/TeamProject/ViewModel/RentViewModel.swift
Labels: 🐞 BugFix, ✨ Feature, 🐸 부용

#62 [Refactor] 마무리 리펙토링
  TeamProject/Model/RegistrationHistory.swift
  TeamProject/TeamProject.xcodeproj/project.pbxproj
  TeamProject/TeamProject/Model/CoreData/KickBoardRecordEntity+CoreDataClass.swift
  TeamProject/TeamProject/Model/CoreData/KickBoardRecordEntity+CoreDataProperties.swift
  TeamProject/TeamProject/Model/CoreData/UsageHistoryEntity+CoreDataClass.swift
  TeamProject/TeamProject/Model/CoreData/UsageHistoryEntity+CoreDataProperties.swift
  TeamProject/TeamProject/Model/Entity/KickBoardRecord.swift
  TeamProject/TeamProject/Model/Entity/Location.swift
  TeamProject/TeamProject/Model/Entity/RegistrationHistory.swift
  TeamProject/TeamProject/Model/Entity/SearchData.swift
  TeamProject/TeamProject/Model/Entity/UsageHistory.swift
  TeamProject/TeamProject/Model/Entity/User.swift
  TeamProject/TeamProject/Model/Entity/ValidationResult.swift
  TeamProject/TeamProject/Model/Manager/CoreDataManager.swift
  TeamProject/TeamProject/Model/Manager/UserDefaultsManager.swift
  TeamProject/TeamProject/Model/Manager/UserManager.swift
  TeamProject/TeamProject/Resource/Info.plist
  TeamProject/TeamProject/Utility/Extensions/Int+.swift
  TeamProject/TeamProject/Utility/Extensions/KeyboardObserver+.swift
  TeamProject/TeamProject/View/AuthView/LoginView/LoginViewController.swift
  TeamProject/TeamProject/View/AuthView/LoginView/ViewComponents/LoginView.swift
  TeamProject/TeamProject/View/AuthView/MembershipView/MembershipViewController.swift
  TeamProject/TeamProject/View/AuthView/MembershipView/ViewComponents/MembershipView.swift
  TeamProject/TeamProject/View/Common/KakaoMapViewController.swift
  TeamProject/TeamProject/View/KickBoardRegisterView/KickBoardRegisterViewController.swift
  TeamProject/TeamProject/View/KickBoardRegisterView/ViewComponets/DeleteModelViewController.swift
  TeamProject/TeamProject/View/KickBoardRegisterView/ViewComponets/RegisterKickboardAlertViewController.swift
  TeamProject/TeamProject/View/MainViewController.swift
  TeamProject/TeamProject/View/MyPageView/HistoryView/RegistrationHistory/RegistrationHistoryViewController.swift
  TeamProject/TeamProject/View/MyPageView/HistoryView/RegistrationHistory/ViewComponents/RegistrationHistoryTableViewCell.swift
  TeamProject/TeamProject/View/MyPageView/HistoryView/RegistrationHistory/ViewComponents/RegistrationHistoryView.swift
  TeamProject/TeamProject/View/MyPageView/HistoryView/UsageHistory/UsageHistoryViewController.swift
  TeamProject/TeamProject/View/MyPageView/HistoryView/UsageHistory/ViewComponents/UsageHistoryTableViewCell.swift
  TeamProject/TeamProject/View/MyPageView/HistoryView/UsageHistory/ViewComponents/UsageHistoryView.swift
  TeamProject/TeamProject/View/MyPageView/MyPageViewController.swift
  TeamProject/TeamProject/View/MyPageView/ViewComponenets/MyPageTableViewCell.swift
  TeamProject/TeamProject/View/MyPageView/ViewComponenets/MyPageView.swift
  TeamProject/TeamProject/View/RentView/ViewComponents/RentModalViewController.swift
  TeamProject/TeamProject/ViewModel/KickBoardRecordViewModel.swift
  TeamProject/TeamProject/ViewModel/RentModalViewModel.swift
  TeamProject/TeamProject/ViewModel/RentViewModel.swift
  TeamProject/TeamProject/protocol/DelegateProtocol.swift
Labels: 🔨 Refactor, 👻 세준, 🐸 부용, 😈 재욱
